# -*- coding: utf-8 -*-
"""Untitled40.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VtFW68NQvh54k0GZCTF_X8Vj5d7ps-Oj
"""

get_ipython().system('pip install -q imbalanced-learn shap xgboost lightgbm')

from google.colab import files

uploaded = files.upload()

import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.utils.class_weight import compute_sample_weight

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    roc_auc_score,
    classification_report,
    confusion_matrix
)

from sklearn.ensemble import RandomForestClassifier, StackingClassifier
from sklearn.linear_model import LogisticRegression

from imblearn.over_sampling import BorderlineSMOTE
from imblearn.under_sampling import TomekLinks

from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
import shap

import os

print(os.listdir('/content'))

DATA_FILE = "/content/cicids2017_binary_balanced.csv"

data = pd.read_csv(DATA_FILE)

data = data.drop_duplicates()
data = data.replace([np.inf, -np.inf], np.nan)
data = data.fillna(0)

# FIX (data integrity): a small number of rows in CICIDS2017 share IDENTICAL
# feature values but have CONFLICTING labels (the same flow appears once as
# Benign, once as Attack) - a known quality issue in this dataset's
# flow-extraction process, not something exact drop_duplicates() catches
# (since the label column differs). These rows are inherently unresolvable
# by any classifier and, if split across train/test, would let the same
# flow "leak" its wrong answer across the split. They are removed here.
feature_cols_check = [c for c in data.columns if c != "Attack_Binary"]
dup_mask = data.duplicated(subset=feature_cols_check, keep=False)
if dup_mask.any():
    group_label_counts = data[dup_mask].groupby(feature_cols_check)["Attack_Binary"].transform("nunique")
    conflicting_idx = group_label_counts[group_label_counts > 1].index
    if len(conflicting_idx) > 0:
        print(f"Dropping {len(conflicting_idx)} rows with identical features but "
              f"conflicting labels (known CICIDS2017 data-quality issue).")
        data = data.drop(index=conflicting_idx)

# Downcast numeric dtypes to shrink memory footprint. Tree-based models do
# not need float64/int64 precision, so this has no meaningful accuracy
# effect but roughly halves RAM use.
for col in data.select_dtypes(include="float64").columns:
    data[col] = pd.to_numeric(data[col], downcast="float")
for col in data.select_dtypes(include="int64").columns:
    data[col] = pd.to_numeric(data[col], downcast="integer")

print("Shape after cleaning:", data.shape)

IMBALANCE_RATIO = 0.02

benign = data[data["Attack_Binary"] == 0]
attack = data[data["Attack_Binary"] == 1]

n_benign = len(benign)
n_attack_target = int((IMBALANCE_RATIO * n_benign) / (1 - IMBALANCE_RATIO))
n_attack_target = min(n_attack_target, len(attack))

attack_sampled = attack.sample(n=n_attack_target, random_state=42)

data = pd.concat([benign, attack_sampled], ignore_index=True)
data = data.sample(frac=1, random_state=42).reset_index(drop=True)  # shuffle

print(f"\nArtificially reconstructed high-imbalance dataset (target ~{IMBALANCE_RATIO:.1%} attack):")
print(data["Attack_Binary"].value_counts())
print(data["Attack_Binary"].value_counts(normalize=True))

TARGET_COL = "Attack_Binary"

y = data[TARGET_COL].values
X = data.drop(columns=[TARGET_COL])

# All columns are already numeric in this dataset - no LabelEncoder step
# needed (unlike the UNSW-NB15 pipeline, which had categorical fields).
assert X.select_dtypes(include="object").shape[1] == 0, (
    "Unexpected non-numeric column(s) found - inspect before proceeding."
)

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("\nTrain class distribution:\n", pd.Series(y_train).value_counts())
print("Test class distribution:\n", pd.Series(y_test).value_counts())

selector = RandomForestClassifier(
    n_estimators=300,
    class_weight="balanced",
    random_state=42,
    n_jobs=-1
)

selector.fit(X_train, y_train)

importance = pd.Series(
    selector.feature_importances_,
    index=X_train.columns
)

selected_features = (
    importance
    .sort_values(ascending=False)
    .head(30)
    .index
)

X_train = X_train[selected_features]
X_test = X_test[selected_features]

print("\nTop selected features:\n", list(selected_features))

min_class_size = pd.Series(y_train).value_counts().min()
k_neighbors = max(1, min(5, int(min_class_size) - 1))

# Oversample the minority (attack) class only PARTIALLY - up to a capped
# fraction of the majority size AND an absolute ceiling - leaving
# deliberate residual imbalance for the cost-sensitive weighting stage to
# meaningfully act on, rather than fully erasing the imbalance here.
TARGET_RATIO = 0.2
MAX_SAMPLES_PER_CLASS = 30000

train_class_counts = pd.Series(y_train).value_counts()
majority_count = train_class_counts.max()

sampling_strategy = {
    cls: min(
        majority_count,
        max(count, min(int(majority_count * TARGET_RATIO), MAX_SAMPLES_PER_CLASS))
    )
    for cls, count in train_class_counts.items()
}

# BorderlineSMOTE and TomekLinks run as two separate sequential steps
# (rather than nested inside SMOTETomek) to avoid a strict type-check
# incompatibility in current imbalanced-learn versions.
borderline_smote = BorderlineSMOTE(
    random_state=42,
    k_neighbors=k_neighbors,
    sampling_strategy=sampling_strategy
)
X_train, y_train = borderline_smote.fit_resample(X_train, y_train)

tomek = TomekLinks()
X_train, y_train = tomek.fit_resample(X_train, y_train)

print("\nPartially balanced training shape:", X_train.shape)
print(pd.Series(y_train).value_counts())

rf = RandomForestClassifier(
    n_estimators=500,
    random_state=42,
    n_jobs=-1
)

xgb = XGBClassifier(
    n_estimators=500,
    learning_rate=0.03,
    max_depth=6,
    eval_metric="logloss",   # binary target here
    random_state=42,
    n_jobs=-1,
    tree_method="hist"
)

lgb = LGBMClassifier(
    n_estimators=500,
    learning_rate=0.03,
    random_state=42,
    n_jobs=-1
)

sample_weight = compute_sample_weight(class_weight="balanced", y=y_train)

model = StackingClassifier(
    estimators=[
        ("RF", rf),
        ("XGB", xgb),
        ("LGBM", lgb)
    ],
    final_estimator=LogisticRegression(max_iter=2000),
    cv=5,
    # n_jobs=None (not -1): RF/XGB/LGBM already parallelize internally;
    # parallelizing the outer stacking folds too causes CPU
    # oversubscription on Colab's limited cores.
    n_jobs=None
)

print("\nTraining model...")
print("Final training set size going into StackingClassifier:", X_train.shape)

model.fit(
    X_train,
    y_train,
    sample_weight=sample_weight
)

# ==========================================================
# SHAP INTERACTION EXPLAINABILITY FOR CICIDS2017 DATASET
# Cost-Sensitive Stacking Ensemble Paper Validation
# ==========================================================


# Install SHAP (run once)
!pip install shap -q


# Import libraries
import shap
import numpy as np
import matplotlib.pyplot as plt


# ----------------------------------------------------------
# 1. Extract LightGBM Base Learner from Stacking Model
# ----------------------------------------------------------

print("Available base models:")
print(model.named_estimators_.keys())


# Change name if your model name is different
lgbm_model = model.named_estimators_["LGBM"]



# ----------------------------------------------------------
# 2. Prepare Feature Names
# ----------------------------------------------------------

try:
    feature_names = X_test.columns.tolist()

except:
    feature_names = [
        f"Feature_{i}"
        for i in range(X_test.shape[1])
    ]


print("Number of features:", len(feature_names))



# ----------------------------------------------------------
# 3. Select Samples for SHAP Interaction
# (Full CICIDS2017 is very large)
# ----------------------------------------------------------

X_shap = X_test[:2000]


print(
    "SHAP sample size:",
    X_shap.shape
)



# ----------------------------------------------------------
# 4. Create SHAP Tree Explainer
# ----------------------------------------------------------

explainer = shap.TreeExplainer(
    lgbm_model
)



# ----------------------------------------------------------
# 5. Calculate SHAP Interaction Values
# ----------------------------------------------------------

print("Calculating SHAP interaction values...")


shap_interaction_values = (
    explainer.shap_interaction_values(
        X_shap
    )
)


print("SHAP interaction calculation completed")



# ----------------------------------------------------------
# 6. SHAP Interaction Summary Plot
# Paper Figure
# ----------------------------------------------------------

plt.figure(
    figsize=(12,8)
)


shap.summary_plot(
    shap_interaction_values,
    X_shap,
    feature_names=feature_names,
    max_display=20,
    show=False
)


plt.title(
    "SHAP Interaction Analysis - CICIDS2017"
)


plt.tight_layout()


plt.savefig(
    "CICIDS2017_SHAP_Interaction.png",
    dpi=300,
    bbox_inches="tight"
)


plt.show()



# ----------------------------------------------------------
# 7. Top Feature Interaction Ranking
# ----------------------------------------------------------

interaction_matrix = np.abs(
    shap_interaction_values
).mean(axis=0)



interaction_list = []


for i in range(len(feature_names)):

    for j in range(i+1, len(feature_names)):

        interaction_list.append(
            (
                feature_names[i],
                feature_names[j],
                interaction_matrix[i,j]
            )
        )



interaction_list = sorted(
    interaction_list,
    key=lambda x:x[2],
    reverse=True
)



print("\nTop 20 Feature Interactions\n")
print("--------------------------------")


for item in interaction_list[:20]:
    print(
        item[0],
        "<-->",
        item[1],
        ":",
        round(item[2],5)
    )



# ----------------------------------------------------------
# 8. Save Interaction Values
# ----------------------------------------------------------

np.save(
    "CICIDS2017_SHAP_interaction_values.npy",
    shap_interaction_values
)


print("\nSHAP Interaction Analysis Completed Successfully")

# Generate predictions

y_pred = model.predict(X_test)

print("Prediction completed")

from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns


# Prediction
y_pred = model.predict(X_test)


# Confusion matrix
cm = confusion_matrix(
    y_test,
    y_pred
)


# Correct CICIDS2017 labels
class_names = [
    "Benign",
    "Attack"
]


# Plot
plt.figure(figsize=(6,5))


sns.heatmap(
    cm,
    annot=True,
    fmt="d",
    cmap="Blues",
    xticklabels=class_names,
    yticklabels=class_names,
    linewidths=0.5
)


plt.xlabel(
    "Predicted Label",
    fontsize=12
)


plt.ylabel(
    "Actual Label",
    fontsize=12
)


plt.title(
    "Confusion Matrix - CICIDS2017 Cost-Sensitive Stacking Ensemble",
    fontsize=13
)


plt.tight_layout()

plt.show()

!pip install shap

import shap
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd



prediction = model.predict(X_test)
probabilities = model.predict_proba(X_test)[:, 1]

print("\nRESULTS")
print("================")

print("Accuracy:", accuracy_score(y_test, prediction))
print("Precision (macro):", precision_score(y_test, prediction, average="macro"))
print("Recall (macro):", recall_score(y_test, prediction, average="macro"))
print("F1 Score (macro):", f1_score(y_test, prediction, average="macro"))
print("ROC-AUC:", roc_auc_score(y_test, probabilities))

print(
    classification_report(
        y_test,
        prediction,
        target_names=["Benign", "Attack"]
    )
)

print(confusion_matrix(y_test, prediction))

try:
    print("Generating SHAP explanation (reduced sample sizes for feasibility)...")

    background = shap.sample(X_train, 50, random_state=42)
    explain_set = X_test.iloc[:50]

    explainer = shap.Explainer(model.predict_proba, background)
    shap_values = explainer(explain_set)

    print("SHAP completed. shap_values shape:", np.array(shap_values.values).shape)

except Exception as e:
    print("SHAP explanation skipped due to an error/timeout risk:", str(e))
    print("Tip: for full-scale SHAP analysis, save the trained model with "
          "joblib and run the explanation as a separate offline script.")

from sklearn.metrics import roc_curve, auc


y_prob = model.predict_proba(
    X_test
)[:,1]


fpr,tpr,threshold = roc_curve(
    y_test,
    y_prob
)


roc_auc = auc(
    fpr,
    tpr
)


plt.figure(figsize=(7,5))


plt.plot(
    fpr,
    tpr,
    label=f"AUC={roc_auc:.4f}"
)


plt.plot(
    [0,1],
    [0,1],
    linestyle="--"
)


plt.xlabel(
"False Positive Rate"
)


plt.ylabel(
"True Positive Rate"
)


plt.title(
"ROC Curve - CICIDS2017"
)


plt.legend()

plt.show()

from sklearn.metrics import precision_recall_curve, auc


precision, recall, threshold = precision_recall_curve(
    y_test,
    y_prob
)


pr_auc = auc(
    recall,
    precision
)


plt.figure(figsize=(7,5))


plt.plot(
    recall,
    precision,
    label=f"PR-AUC={pr_auc:.4f}"
)


plt.xlabel(
"Recall"
)


plt.ylabel(
"Precision"
)


plt.title(
"Precision-Recall Curve"
)


plt.legend()

plt.show()

lgbm_model = model.named_estimators_["LGBM"]

import shap


explainer = shap.TreeExplainer(
    lgbm_model
)


shap_values = explainer.shap_values(
    X_test
)

feature_names = X_train.columns.tolist()

print(data.shape)

print(data.duplicated().sum())

print(data.columns.tolist())